"""

Write a Python program to create a dictionary with the same keys as the given dictionary and values generated by
running the given function for each value.

{
    'Theodore': {'user': 'Theodore', 'age': 45},
    'Roxanne': {'user': 'Roxanne', 'age': 15},
    'Mathew': {'user': 'Mathew', 'age': 21}
}


lambda u: u['age']  =>  {'Theodore': 45, 'Roxanne': 15, 'Mathew': 21}

"""


def main():
    d = {
        'Theodore': {'user': 'Theodore', 'age': 45},
        'Roxanne': {'user': 'Roxanne', 'age': 15},
        'Mathew': {'user': 'Mathew', 'age': 21}
    }

    f = lambda u: u['age']
    print({k: f(v) for k, v in d.items()})



if __name__ == "__main__":
    main()
